add_newline = false
command_timeout = 60
format = """\
$os\
$directory \
$git_branch$git_status\
$line_break\
$character\
"""

right_format = """\
$time\
"""

palette = "colors"

[palettes.colors]
mustard = '#af8700' # example
primary = '#ffb4a7'
color2 = '#561e16'
color3 = '#d8c2be'
color4 = '#271d1c'
color5 = '#561e16'
color6 = '#1a1110'
color7 = '#1a1110'
color8 = '#ffb4a7'
color9 = '#ddc48c'

[directory]
style = "fg:#ffb4a7 bold" 
home_symbol = ""
read_only = "󰌾"
read_only_style = "fg:red" 
fish_style_pwd_dir_length = 2
format = "[ $path ]($style)[$read_only]($read_only_style)"

[directory.substitutions]
"Desktop" = " "
"Documents" = ""
"Downloads" = ""
"Music" = "󰎈"
"Pictures" = ""
"Images" = ""
"Videos" = ""
"Vidéos" = ""
"GitHub" = "󰊤"
"vaults" = "󰂺"
"personal" = "󰛓"
".config" = ""

[character]
success_symbol = '[](fg:#ffb4a7 bold)'
error_symbol = '[](fg:#ffb4ab bold)'
vicmd_symbol = '[](fg:#1a1110 bold)'

[git_branch]
style = "fg:#ddc48c bold" # color9 (red)
format = '[$symbol$branch]($style) '

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[($all_status$ahead_behind )](fg:#ea6962)]($style)'
# style = "bg:#394260"

[os]
format = "[$symbol]($style)"
style = "fg:#ffb4a7 bold" # color8
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[time]
 disabled = false
 format = '[ ](#e7bdb6)[[ $time ](fg:#e7bdb6 )]($style)'
 time_format = "%R"

[line_break]
disabled = true
