# Gruvbox Dark Hard Palette
# fg: ebdbb2 | red: fb4934 | orange: fe8019 | yellow: fabd2f
# green: b8bb26 | aqua: 8ec07c | blue: 83a598 | purple: d3869b
# bg0_hard: 1d2021 | bg1: 3c3836 | bg2: 504945

# syntax highlighting variables
fish_color_normal ebdbb2
fish_color_command 8ec07c
fish_color_keyword 83a598
fish_color_quote fabd2f
fish_color_redirection ebdbb2
fish_color_end fe8019
fish_color_error fb4934
fish_color_param d3869b
fish_color_comment 928374
fish_color_selection --background=504945
fish_color_operator b8bb26
fish_color_escape 83a598
fish_color_autosuggestion 928374
fish_color_cwd b8bb26
fish_color_cwd_root fb4934
fish_color_user fabd2f
fish_color_host 83a598
fish_color_host_remote d3869b
fish_color_cancel ebdbb2
fish_color_search_match --background=3c3836
fish_color_valid_path

# pager color variables
fish_pager_color_progress 928374
fish_pager_color_background --background=1d2021
fish_pager_color_prefix 8ec07c
fish_pager_color_completion ebdbb2
fish_pager_color_description 928374

fish_pager_color_secondary_background --background=3c3836
fish_pager_color_secondary_prefix 8ec07c
fish_pager_color_secondary_completion ebdbb2
fish_pager_color_secondary_description 928374

fish_pager_color_selected_background --background=504945
fish_pager_color_selected_prefix 8ec07c
fish_pager_color_selected_completion ebdbb2
fish_pager_color_selected_description ebdbb2
