#Matugen

# Syntax Highlighting Colors
fish_color_normal {{colors.on_surface.default.hex_stripped}}
fish_color_command {{colors.primary.default.hex_stripped}}
fish_color_keyword {{colors.tertiary.default.hex_stripped}}
fish_color_quote {{colors.secondary.default.hex_stripped}}
fish_color_redirection {{colors.on_surface.default.hex_stripped}}
fish_color_end ff9e64
fish_color_option {{colors.tertiary.default.hex_stripped}}
fish_color_error {{colors.error.default.hex_stripped}}
fish_color_param {{colors.tertiary.default.hex_stripped}}
fish_color_comment {{colors.on_surface_variant.default.hex_stripped}}
fish_color_selection --background={{colors.primary.default.hex_stripped}}
fish_color_search_match --background={{colors.primary.default.hex_stripped}}
fish_color_operator 9ece6a
fish_color_escape {{colors.tertiary.default.hex_stripped}}
fish_color_autosuggestion {{colors.on_surface_variant.default.hex_stripped}}

# Completion Pager Colors
fish_pager_color_progress {{colors.on_surface_variant.default.hex_stripped}}
fish_pager_color_prefix {{colors.primary.default.hex_stripped}}
fish_pager_color_completion {{colors.on_surface_variant.default.hex_stripped}}
fish_pager_color_description {{colors.on_surface_variant.default.hex_stripped}}
fish_pager_color_selected_background --background={{colors.surface_container_low.default.hex_stripped}}