# vim:ft kitty

## name: Horizon Extended
## license: MIT
## author: Lance Wilhelm
## upstream: 

background {hex.bg}
foreground {hex.fg}
selection_background {hex.accent}
selection_foreground {hex.bg}
url_color {hex.accent}
cursor {hex.fg}
cursor_text_color {hex.bg}

# Tabs
active_tab_background {hex.accent}
active_tab_foreground {hex.bg}
inactive_tab_background {hex.bg}
inactive_tab_foreground {hex.alt_bg}
#tab_bar_background 

# Windows
active_border_color {hex.accent}
inactive_border_color {hex.bg}

# normal
color0 {hex.alt_fg}
color1 {hex.red}
color2 {hex.green}
color3 {hex.yellow}
color4 {hex.blue}
color5 {hex.mauve}
color6 {hex.blue}
color7 {hex.fg}

# brignt
color8 {hex.alt_fg}
color9 {hex.red}
color10 {hex.green}
color11 {hex.yellow}
color12 {hex.blue}
color13 {hex.mauve}
color14 {hex.blue}
color15 {hex.fg}
