# Core Colors
background            #161217
foreground            #e8e0e8
selection_foreground  #deb8f7
selection_background  #402357
cursor                #deb8f7
cursor_text_color     #161217

# Regular Colors
color0  #161217               
color1  #ffb4ab                 
color2  #deb8f7               
color3  #f4b7bb              
color4  #f2daff  
color5  #eeddf5
color6  #d2c1d9             
color7  #e8e0e8            

# Bright Colors
color8  #3c383e         
color9  #ffb4ab                  
color10 #deb8f7                
color11 #f4b7bb               
color12 #f2daff   
color13 #eeddf5 
color14 #d2c1d9              
color15 #e8e0e8             