# Core Colors
background            #0f1417
foreground            #dfe3e7
selection_foreground  #8ccff0
selection_background  #003547
cursor                #8ccff0
cursor_text_color     #0f1417

# Regular Colors
color0  #0f1417               
color1  #ffb4ab                 
color2  #8ccff0               
color3  #c7c2ea              
color4  #bfe8ff  
color5  #d0e6f3
color6  #b4cad6             
color7  #dfe3e7            

# Bright Colors
color8  #353a3d         
color9  #ffb4ab                  
color10 #8ccff0                
color11 #c7c2ea               
color12 #bfe8ff   
color13 #d0e6f3 
color14 #b4cad6              
color15 #dfe3e7             