# Core Colors
background            #16130b
foreground            #eae1d4
selection_foreground  #e4c36c
selection_background  #3d2e00
cursor                #e4c36c
cursor_text_color     #16130b

# Regular Colors
color0  #16130b               
color1  #ffb4ab                 
color2  #e4c36c               
color3  #aecfad              
color4  #ffdf91  
color5  #f2e1bb
color6  #d6c5a0             
color7  #eae1d4            

# Bright Colors
color8  #3d392f         
color9  #ffb4ab                  
color10 #e4c36c                
color11 #aecfad               
color12 #ffdf91   
color13 #f2e1bb 
color14 #d6c5a0              
color15 #eae1d4             