###################
### DEFAULT PROGRAMS ###
###################

env=TERMINAL,kitty
$fileManager = nautilus -w
$menu = rofi -show drun -i --theme ~/.config/hyprlab/rofi/themes/alt.rasi
$browser = $HOME/Applications/zen_a82c08d732cf3ff177397c6dc4de9937.AppImage
