###################
### DEFAULT PROGRAMS ###
###################

$applist = ~/.config/hyprlab/rofi/themes/applist.rasi
$appmenu = ~/.config/hyprlab/rofi/themes/config.rasi

env=TERMINAL,kitty
$fileManager = nautilus -w
$menu = rofi -show drun -i -theme $applist
$browser = $HOME/Applications/zen_a82c08d732cf3ff177397c6dc4de9937.AppImage
