###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nautilus -w
$menu = rofi -show drun -i --theme ~/.config/hyprlab/rofi/themes/alt.rasi
$browser = /opt/zen/zen
