source = $hyprlab/hyprland/profiles/current/monitors

workspace = special:ai, on-created-empty:exec gtk-launch WebApp-ChatGPT3504

workspace = 1, persistent:true, monitor:$VAR_PRIMARY, default:true
workspace = 2, persistent:true, monitor:$VAR_PRIMARY
workspace = 3, persistent:true, monitor:$VAR_PRIMARY
workspace = 4, persistent:true, monitor:$VAR_PRIMARY
workspace = 5, persistent:true, monitor:$VAR_PRIMARY
workspace = 6, persistent:true, monitor:$VAR_SECONDARY, default:true
workspace = 7, persistent:true, monitor:$VAR_SECONDARY,
workspace = 8, persistent:true, monitor:$VAR_SECONDARY,
workspace = 9, persistent:true, monitor:$VAR_SECONDARY,
workspace = 10, persistent:true, monitor:$VAR_SECONDARY,

workspace = name:󰊗, monitor:$PRIMARY, default:true


