# ┏┓━┏┓┏┓━━┏┓┏━━━┓┏━━━┓┏━━━┓┏┓━━━┏━━━┓┏━━┓━
# ┃┃━┃┃┃┗┓┏┛┃┃┏━┓┃┃┏━━┛┃┏━┓┃┃┃━━━┃┏━┓┃┃┏┓┃━
# ┃┗━┛┃┗┓┗┛┏┛┃┗━┛┃┃┗━━┓┃┗━┛┃┃┃━━━┃┃━┃┃┃┗┛┗┓
# ┃┏━┓┃━┗┓┏┛━┃┏━━┛┃┏━━┛┃┏┓┏┛┃┃━┏┓┃┗━┛┃┃┏━┓┃
# ┃┃━┃┃━━┃┃━━┃┃━━━┃┗━━┓┃┃┃┗┓┃┗━┛┃┃┏━┓┃┃┗━┛┃
# ┗┛━┗┛━━┗┛━━┗┛━━━┗━━━┛┗┛┗━┛┗━━━┛┗┛━┗┛┗━━━┛
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

$hyprlab = $HOME/.config/hyprlab
$scripts = $hyprlab/scripts
$monitor = $hyprlab/hyprland/monitors_profile/current
$folder = $hyprlab/hyprland/profiles/current

#default apps
source = $folder/apps.conf

#Colors of the hyprland borders and some hyprlock element
source = $hyprlab/hyprland/conf/colors.conf

#monitors configs
source = $monitor

#autostart configs
source = $folder/autostart.conf

#environement variablesss
source = $folder/env.conf

#decorations / effects / animations configs
source = $folder/decorations.conf
source = $folder/animations.conf

#plugins configs
source = $folder/plugins.conf

#workspaces configs
source = $folder/workspace.conf

#keybinds config
source = $folder/keybinds.conf

#window rules
source = $folder/windowrule.conf

#input configs
source = $folder/input.conf

#base settings

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}
master {
    new_status = master
}

