# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# XWAYLAND
windowrule = no_focus 1,match:class ^$,match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
windowrule = no_blur 1, match:class ^(\bresolve\b)$, match:xwayland 1
windowrule = no_blur 1, match:class ^()$, match:xwayland 1

#dialogs
windowrule = float 1,match:class ^(dialog)$
windowrule = float 1,match:class ^(splash)$

windowrule {
    name = ai
    match:workspace = special:ai
    match:class = ^(WebApp-ChatGPT3504)
    float = on
    center = on
    size = 1000 700
}

windowrule {
    name = pip
    match:title = ^(Picture-in-Picture)$
    float = on
    size = 800 500
}

windowrule {
    name = files
    match:title = ^(Open File|Save File|Select File|Select Folder|Save As)$
    float = on
    center = on
    size = 50% 50%
}

windowrule {
    name = xwayland_files
    match:class = ^(Xdg-desktop-portal-gtk)$
    float = on
    center = on
    size = 50% 50%
    no_blur = on
    no_shadow = on
    border_size = 0
}

windowrule {
    name = float_class
    match:class = ^(float)$
    float = on
    center = on 
    size = 1300 800
}

windowrule {
    name = float_tag
    match:tag = ^(float)$
    float = on
    center = on 
    size = 800 600
}

windowrule {
    name = games
    match:tag = game
    workspace = name:󰊗
    fullscreen = on
    immediate = on
}

#TAGS
windowrule=tag +game, match:initial_class ^(steam_app_\d+)
windowrule=tag +float, match:class ^(nm-connection-editor)$
windowrule=tag +float, match:class ^(org.pulseaudio.pavucontrol)$
windowrule=tag +float, match:class ^(blueman-manager)$

#rofi
layerrule {
    name = rofi_layer
    match:namespace = rofi
    blur = on
    ignore_alpha = 0.2
    animation = slide bottom
}

#SWAYNC
layerrule {
    name = swaync-control
    match:namespace = swaync-control-center
    animation = slide right
    blur = on
    ignore_alpha = 0.2
}

layerrule {
    name = swaync-notif
    match:namespace = swaync-notification-window
    animation = slide top
    blur = on
    ignore_alpha = 0.2
}

layerrule {
    name = waybar
    match:namespace = waybar
    blur = on
    ignore_alpha = 0.2
}

layerrule {
    name = wlogout
    match:namespace = logout_dialog
    blur = on 
    ignore_alpha = 0.1
}

