workspace = special:ai, on-created-empty:exec gtk-launch WebApp-ChatGPT3504
windowrulev2= float,center,size 1000 700,opacity 1 override,onworkspace:special:ai, class:^(WebApp-ChatGPT3504)

workspace = 1, persistent:true, monitor:$PRIMARY, default:true
workspace = 2, persistent:true, monitor:$PRIMARY
workspace = 3, persistent:true, monitor:$PRIMARY
workspace = 4, persistent:true, monitor:$PRIMARY
workspace = 5, persistent:true, monitor:$PRIMARY
workspace = 6, persistent:true, monitor:$SECOND, default:true
workspace = 7, persistent:true, monitor:$SECOND,
workspace = 8, persistent:true, monitor:$SECOND,
workspace = 9, persistent:true, monitor:$SECOND,
workspace = 10, persistent:true, monitor:$SECOND,

workspace = name:󰊗, monitor:$PRIMARY, default:true
windowrulev2 = fullscreen, onworkspace:name:󰊗


