# Template color Palette

# syntax highlighting variables
fish_color_normal {hhex.fg}
fish_color_command {hhex.accent}
fish_color_keyword {hhex.blue}
fish_color_quote {hhex.tertiary}
fish_color_redirection {hhex.fg}
fish_color_end {hhex.tertiary}
fish_color_error {hhex.red}
fish_color_param {hhex.secondary}
fish_color_comment {hhex.alt_fg}
fish_color_selection --background={hhex.alt_bg}
fish_color_operator {hhex.secondary}
fish_color_escape {hhex.blue}
fish_color_autosuggestion {hhex.alt_fg}
fish_color_cwd {hhex.secondary}
fish_color_cwd_root {hhex.red}
fish_color_user {hhex.yellow}
fish_color_host {hhex.blue}
fish_color_host_remote {hhex.secondary}
fish_color_cancel {hhex.fg}
fish_color_search_match --background={hhex.alt_bg}
fish_color_valid_path

# pager color variables
fish_pager_color_progress {hhex.surface}
fish_pager_color_background --background={hhex.bg}
fish_pager_color_prefix {hhex.accent}
fish_pager_color_completion {hhex.fg}
fish_pager_color_description {hhex.surface}

fish_pager_color_secondary_background --background={hhex.alt_bg}
fish_pager_color_secondary_prefix {hhex.accent}
fish_pager_color_secondary_completion {hhex.fg}
fish_pager_color_secondary_description {hhex.surface}

fish_pager_color_selected_background --background={hhex.alt_bg}
fish_pager_color_selected_prefix {hhex.accent}
fish_pager_color_selected_completion {hhex.fg}
fish_pager_color_selected_description {hhex.fg}
