# vim:ft kitty

## name: Horizon Extended
## license: MIT
## author: Lance Wilhelm
## upstream: 

background #1a1513
foreground #f0e4dc
selection_background #e8b89a
selection_foreground #1a1513
url_color #e8b89a
cursor #f0e4dc
cursor_text_color #1a1513

# Tabs
active_tab_background #e8b89a
active_tab_foreground #1a1513
inactive_tab_background #1a1513
inactive_tab_foreground #2e2520
#tab_bar_background 

# Windows
active_border_color #e8b89a
inactive_border_color #1a1513

# normal
color0 #78716c
color1 #e8a090
color2 #c8b888
color3 #e8c8a0
color4 #b8b098
color5 #d8a8a0
color6 #b8b098
color7 #f0e4dc

# brignt
color8 #78716c
color9 #e8a090
color10 #c8b888
color11 #e8c8a0
color12 #b8b098
color13 #d8a8a0
color14 #b8b098
color15 #f0e4dc
